// <auto-generated />
namespace ltap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mot_hai_ba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mot_hai_ba));
        
        string IMigrationMetadata.Id
        {
            get { return "202110051645038_mot_hai_ba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
